language: php

php:
    - 7.4
    - 8.0
    - nightly

cache:
    directories:
        - /home/travis/.composer/cache

matrix:
    allow_failures:
        - php: nightly

install:
    - composer install --dev

script:
    - vendor/bin/phpunit
